name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Base de código
        uses: actions/checkout@v3.6.0

      - name: Docker Hub Login
        uses: docker/login-action@v2.2.0
        with: 
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
   

              
 
